platform :ios, '8.0'

target 'OtpSecureShowcase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OtpSecureShowcase
  pod 'OtpSecure', '2.0.1'

end
