platform :ios, '12.1'

target 'OtpSecureShowcase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OtpSecureShowcase
  pod 'OtpSecure', '1.0.0'

end
